import { useState, useEffect } from 'react'
import { useParams, useNavigate } from 'react-router-dom'
import axios from 'axios'

const EFFORT_COLORS = { S: 'text-emerald-400 bg-emerald-900/30', M: 'text-amber-400 bg-amber-900/30', L: 'text-red-400 bg-red-900/30' }
const EFFORT_LABELS = { S: 'Small', M: 'Medium', L: 'Large' }

function TaskCard({ task, index }) {
  const [expanded, setExpanded] = useState(false)
  return (
    <div className="glass rounded-xl border border-slate-700/50 hover:border-blue-500/30 transition-all">
      <button onClick={() => setExpanded(e => !e)} className="w-full p-4 text-left">
        <div className="flex items-start gap-3">
          <span className="flex-shrink-0 w-6 h-6 rounded-full bg-blue-600/20 border border-blue-500/30 flex items-center justify-center text-xs font-bold text-blue-400 mt-0.5">
            {index + 1}
          </span>
          <div className="flex-1 min-w-0">
            <div className="flex items-center gap-2 flex-wrap">
              <h3 className="font-semibold text-white">{task.title}</h3>
              <span className={`text-xs px-2 py-0.5 rounded-full font-semibold ${EFFORT_COLORS[task.effort]}`}>
                {EFFORT_LABELS[task.effort] || task.effort}
              </span>
              <span className="text-xs text-slate-500">{task.owner}</span>
            </div>
          </div>
          <span className="text-slate-500 text-sm ml-2">{expanded ? '▲' : '▼'}</span>
        </div>
      </button>
      {expanded && (
        <div className="px-4 pb-4 pt-1 border-t border-slate-700/50">
          <p className="text-slate-300 text-sm mb-4 leading-relaxed">{task.description}</p>
          <div className="flex items-start gap-2 bg-emerald-900/20 border border-emerald-500/20 rounded-lg p-3">
            <span className="text-emerald-400 text-sm">✅</span>
            <div>
              <p className="text-xs font-semibold text-emerald-400 uppercase tracking-wide mb-1">Definition of Done</p>
              <p className="text-sm text-slate-300">{task.definition_of_done}</p>
            </div>
          </div>
        </div>
      )}
    </div>
  )
}

export default function Roadmap() {
  const { sessionId } = useParams()
  const navigate = useNavigate()
  const [roadmap, setRoadmap] = useState(null)
  const [region, setRegion] = useState('')
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState(null)

  useEffect(() => {
    axios.post(`/api/sessions/${sessionId}/roadmap`)
      .then(res => {
        setRoadmap(res.data.roadmap)
        setRegion(res.data.region)
        setLoading(false)
      })
      .catch(e => {
        setError('Failed to generate roadmap')
        setLoading(false)
      })
  }, [sessionId])

  if (loading) return (
    <div className="min-h-screen flex items-center justify-center pt-16">
      <div className="text-center max-w-sm">
        <div className="w-16 h-16 border-2 border-blue-500 border-t-transparent rounded-full animate-spin mx-auto mb-6" />
        <h2 className="text-xl font-bold mb-2">Generating your roadmap</h2>
        <p className="text-slate-400 text-sm">Gemini AI is analysing your assessment answers and creating a personalised 90-day Zero Trust plan...</p>
      </div>
    </div>
  )

  if (error) return (
    <div className="min-h-screen flex items-center justify-center pt-16">
      <div className="text-center">
        <p className="text-red-400 mb-4">{error}</p>
        <button onClick={() => navigate(-1)} className="px-6 py-2 bg-slate-700 rounded-lg">Go Back</button>
      </div>
    </div>
  )

  const phases = [
    { key: '30_day', label: '30 Days', color: 'text-blue-400', bg: 'bg-blue-600/20', border: 'border-blue-500/30', dot: 'bg-blue-500', desc: 'Highest priority — quick wins' },
    { key: '60_day', label: '60 Days', color: 'text-violet-400', bg: 'bg-violet-600/20', border: 'border-violet-500/30', dot: 'bg-violet-500', desc: 'Medium-term improvements' },
    { key: '90_day', label: '90 Days', color: 'text-emerald-400', bg: 'bg-emerald-600/20', border: 'border-emerald-500/30', dot: 'bg-emerald-500', desc: 'Strategic changes' },
  ]

  return (
    <div className="min-h-screen pt-20 pb-16">
      <div className="max-w-4xl mx-auto px-4">
        {/* Header */}
        <div className="mb-8 text-center">
          <div className="inline-flex items-center gap-2 px-4 py-2 rounded-full glass text-blue-400 text-sm font-medium mb-4">
            <span>✨</span> Generated by Gemini AI
          </div>
          <h1 className="text-3xl font-extrabold mb-2">Your Zero Trust Roadmap</h1>
          <p className="text-slate-400">Personalised 90-day plan tailored to your gaps and {region} regulatory context</p>
        </div>

        {/* Timeline visual */}
        <div className="flex items-center gap-0 mb-10 max-w-2xl mx-auto">
          {phases.map((p, i) => (
            <div key={p.key} className="flex items-center flex-1">
              <div className="flex flex-col items-center flex-1">
                <div className={`w-4 h-4 rounded-full ${p.dot} shadow-lg`} />
                <div className={`text-sm font-bold ${p.color} mt-1`}>{p.label}</div>
                <div className="text-xs text-slate-600 text-center">{p.desc}</div>
              </div>
              {i < phases.length - 1 && (
                <div className="flex-1 h-0.5 bg-gradient-to-r from-blue-500 via-violet-500 to-emerald-500 mx-2" />
              )}
            </div>
          ))}
        </div>

        {/* Phase sections */}
        <div className="space-y-8">
          {phases.map(phase => (
            <div key={phase.key}>
              <div className={`inline-flex items-center gap-2 px-4 py-2 rounded-xl ${phase.bg} border ${phase.border} mb-4`}>
                <span className={`w-2 h-2 rounded-full ${phase.dot}`} />
                <span className={`font-bold ${phase.color}`}>{phase.label}</span>
                <span className="text-slate-500 text-sm">— {phase.desc}</span>
              </div>
              <div className="space-y-3">
                {(roadmap[phase.key] || []).map((task, i) => (
                  <TaskCard key={i} task={task} index={i} />
                ))}
              </div>
            </div>
          ))}
        </div>

        {/* Actions */}
        <div className="mt-10 flex flex-wrap gap-4 justify-center">
          <button
            onClick={() => navigate(`/dashboard/${sessionId}`)}
            className="px-6 py-3 border border-slate-700 text-slate-400 hover:text-white hover:border-slate-600 rounded-xl transition-all"
          >
            ← Back to Dashboard
          </button>
          <button
            onClick={() => navigate('/playbooks')}
            className="px-6 py-3 bg-slate-700 hover:bg-slate-600 text-white font-semibold rounded-xl transition-all"
          >
            📋 View Playbooks
          </button>
        </div>
      </div>
    </div>
  )
}
